# -*- coding: utf-8 -*-
"""Public Sentiment Collection Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1On9i4SrYBVQqG-Fex5up9o3Eo1Y6mWls

# Public Sentiment Collection Workflow (Enhanced v1)

## 1. Introduction

### 1.1. Lab Overview

This is an **enhanced version** of the public sentiment analysis pipeline that addresses critical credibility concerns:

**🎯 New Features:**
- **Geographic filtering** - Analyze sentiment by region/country
- **Source diversity tracking** - Monitor news, social media, forums, blogs
- **Credibility scoring** - Detect bias, sample size issues, temporal drift
- **Comparative analysis** - Side-by-side regional comparisons
- **Bias warnings** - Automatic detection of skewed data

### 1.2. 🚨 Why Credibility Matters

**Example: "Public opinion on alcohol consumption"**

❌ **Without geographic filtering:**
- Global sentiment: 60% negative, 30% neutral, 10% positive
- **MISLEADING:** Lumps Saudi Arabia + Germany together

✅ **With geographic filtering:**
- Saudi Arabia: 95% negative (religious/cultural)
- Germany: 70% positive (beer culture)
- USA: 50/50 split (health concerns vs. social acceptance)
- **ACCURATE:** Shows cultural nuance

### 1.3. 📋 Learning Outcomes

You will learn how to:
- Implement **geographic sentiment analysis**
- Track **source diversity** and detect bias
- Calculate **credibility scores** for sentiment data
- Generate **comparative regional reports**
- Identify and warn about **sampling limitations**

## 2. Setup: Install Libraries and Configure Environment
"""

# Install required packages for Google Colab
!pip install -q google-generativeai tavily-python matplotlib wordcloud seaborn pandas python-dotenv pycountry

# =========================
# Imports
# =========================

import json
import os
import re
from datetime import datetime, timedelta
from collections import Counter
from urllib.parse import urlparse

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import google.generativeai as genai
from tavily import TavilyClient
from IPython.display import Markdown, display, HTML

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 10

# =========================
# API Configuration
# =========================

try:
    from google.colab import userdata
    GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
    TAVILY_API_KEY = userdata.get('TAVILY_API_KEY')
except:
    GOOGLE_API_KEY = ""  # Paste your Google AI Studio API key here
    TAVILY_API_KEY = ""  # Paste your Tavily API key here

genai.configure(api_key=GOOGLE_API_KEY)
tavily_client = TavilyClient(api_key=TAVILY_API_KEY)
model = genai.GenerativeModel('gemini-2.0-flash-exp')

print("✅ APIs configured successfully")

"""## 3. Utility Functions"""

# =========================
# Utility Functions
# =========================

def log_agent_title_html(title: str, emoji: str):
    html = f"""
    <div style="border:2px solid #3b82f6; border-left:8px solid #2563eb; background:#dbeafe;
                border-radius:8px; padding:16px; margin:16px 0; color:#1e3a8a;">
        <h3 style="margin:0;">{emoji} {title}</h3>
    </div>
    """
    display(HTML(html))

def log_tool_call_html(tool_name: str, args: str = ""):
    html = f"""
    <div style="border:1px solid #a855f7; border-left:4px solid #9333ea; background:#f3e8ff;
                border-radius:6px; padding:12px; margin:8px 0; color:#581c87;">
        <strong>🔧 Tool Call:</strong> <code>{tool_name}</code>
        {f'<br><small>Args: {args[:100]}...</small>' if args else ''}
    </div>
    """
    display(HTML(html))

def log_tool_result_html(result: str):
    result_preview = str(result)[:200] + "..." if len(str(result)) > 200 else str(result)
    html = f"""
    <div style="border:1px solid #10b981; border-left:4px solid #059669; background:#d1fae5;
                border-radius:6px; padding:12px; margin:8px 0; color:#065f46;">
        <strong>✅ Result:</strong> <code>{result_preview}</code>
    </div>
    """
    display(HTML(html))

def log_final_summary_html(summary: str):
    html = f"""
    <div style="border:2px solid #f59e0b; border-left:8px solid #d97706; background:#fef3c7;
                border-radius:8px; padding:16px; margin:16px 0; color:#78350f;">
        <strong>📋 Agent Summary:</strong><br>
        <div style="margin-top:8px; white-space:pre-wrap;">{summary}</div>
    </div>
    """
    display(HTML(html))

def log_warning_html(warning: str):
    html = f"""
    <div style="border:2px solid #ef4444; border-left:8px solid #dc2626; background:#fee2e2;
                border-radius:8px; padding:16px; margin:16px 0; color:#7f1d1d;">
        <strong>⚠️ Credibility Warning:</strong><br>
        <div style="margin-top:8px;">{warning}</div>
    </div>
    """
    display(HTML(html))

print("✅ Utility functions loaded")

"""## 4. Enhanced Tool Definitions

### 4.1. Geographic Web Search Tool

This enhanced version supports **location-based filtering**.
"""

# =========================
# Tool: Geographic Web Search
# =========================

def tavily_search_geographic(
    query: str,
    location: str = None,
    max_results: int = 15,
    days_back: int = 365
) -> dict:
    """
    Search with optional geographic filtering.

    Args:
        query (str): Search query
        location (str): Country/region (e.g., "USA", "Germany", "Saudi Arabia", "global")
        max_results (int): Maximum results
        days_back (int): How many days back to search

    Returns:
        dict: Search results with metadata
    """
    # Add location to query if specified
    search_query = query
    if location and location.lower() != "global":
        search_query = f"{query} {location}"

    try:
        response = tavily_client.search(
            query=search_query,
            max_results=max_results,
            search_depth="advanced",
            days=days_back
        )

        results = []
        for item in response.get('results', []):
            # Extract domain for source tracking
            url = item.get('url', '')
            domain = urlparse(url).netloc if url else 'unknown'

            results.append({
                'title': item.get('title', ''),
                'content': item.get('content', ''),
                'url': url,
                'domain': domain,
                'score': item.get('score', 0)
            })

        return {
            'results': results,
            'query': search_query,
            'location': location or "global",
            'count': len(results)
        }
    except Exception as e:
        return {'error': str(e), 'results': []}

print("✅ Geographic search tool loaded")

"""### 4.2. Source Diversity Analyzer"""

# =========================
# Tool: Source Diversity Analysis
# =========================

def analyze_source_diversity(results: list) -> dict:
    """
    Analyze diversity of information sources.

    Returns:
        dict: Diversity metrics and warnings
    """
    domains = [r.get('domain', 'unknown') for r in results]
    domain_counts = Counter(domains)

    # Classify source types using domain patterns
    source_types = []
    for domain in domains:
        if any(x in domain for x in ['reddit.com', 'twitter.com', 'facebook.com', 'instagram.com']):
            source_types.append('social_media')
        elif any(x in domain for x in ['news', 'times', 'post', 'bbc', 'cnn', 'guardian']):
            source_types.append('news')
        elif any(x in domain for x in ['.gov', '.edu']):
            source_types.append('institutional')
        elif 'blog' in domain or 'medium.com' in domain:
            source_types.append('blog')
        else:
            source_types.append('other')

    type_counts = Counter(source_types)

    # Calculate diversity score (0-100)
    unique_domains = len(domain_counts)
    total_sources = len(domains)

    # Higher score = more diverse
    diversity_score = min(100, (unique_domains / max(1, total_sources)) * 150)

    # Detect concentration bias
    warnings = []
    most_common_domain, max_count = domain_counts.most_common(1)[0] if domain_counts else ('', 0)
    if max_count > total_sources * 0.4:
        warnings.append(f"⚠️ {(max_count/total_sources)*100:.0f}% of sources from single domain: {most_common_domain}")

    if type_counts.get('social_media', 0) > total_sources * 0.7:
        warnings.append("⚠️ Over 70% sources are social media (potential echo chamber bias)")

    if unique_domains < 5:
        warnings.append(f"⚠️ Only {unique_domains} unique sources (low diversity)")

    return {
        'diversity_score': round(diversity_score, 1),
        'unique_domains': unique_domains,
        'total_sources': total_sources,
        'source_type_distribution': dict(type_counts),
        'top_domains': dict(domain_counts.most_common(5)),
        'warnings': warnings
    }

print("✅ Source diversity analyzer loaded")

"""### 4.3. Sentiment Analysis with Geographic Detection"""

# =========================
# Tool: Enhanced Sentiment Analysis
# =========================

def analyze_sentiment_with_context(texts: list, issue: str) -> list:
    """
    Analyze sentiment with cultural/geographic context awareness.
    """
    prompt = f"""
You are a cross-cultural sentiment analysis expert analyzing: "{issue}"

For each text snippet, provide:
1. Overall sentiment: positive, negative, or neutral
2. Primary emotion: fear, anger, hope, joy, sadness, skepticism, curiosity
3. Key themes (max 3)
4. Sentiment intensity: low, medium, high
5. Detected cultural/geographic context (if any): e.g., "Western", "Middle Eastern", "Asian", "Global"

Text snippets:
{json.dumps(texts[:20], indent=2)}

Respond ONLY with valid JSON:
{{
  "analyses": [
    {{
      "text_index": 0,
      "sentiment": "positive/negative/neutral",
      "emotion": "fear/anger/hope/joy/sadness/skepticism/curiosity",
      "themes": ["theme1", "theme2"],
      "intensity": "low/medium/high",
      "cultural_context": "Western/Middle Eastern/Asian/Global/Unknown"
    }}
  ]
}}
"""

    try:
        response = model.generate_content(prompt)
        text = response.text.strip()
        json_match = re.search(r'\{.*\}', text, re.DOTALL)
        if json_match:
            result = json.loads(json_match.group(0))
            return result.get('analyses', [])
        else:
            return [{"error": "No JSON in response"}]
    except Exception as e:
        return [{"error": str(e)}]

print("✅ Enhanced sentiment analysis tool loaded")

"""## 5. Enhanced Agent Definitions

### 5.1. Geographic Social Listening Agent
"""

# =========================
# Agent 1: Geographic Social Listening
# =========================

def geographic_listening_agent(
    issue_keyword: str,
    locations: list = ["global"],
    num_sources_per_location: int = 15
) -> dict:
    """
    Collect data with geographic segmentation.

    Args:
        issue_keyword (str): Topic to research
        locations (list): List of countries/regions (e.g., ["USA", "Germany", "Saudi Arabia"])
        num_sources_per_location (int): Sources per location

    Returns:
        dict: Data organized by location
    """
    log_agent_title_html("Geographic Social Listening Agent", "🌍")

    location_data = {}

    for location in locations:
        log_tool_call_html("tavily_search_geographic", f"location={location}")

        search_result = tavily_search_geographic(
            query=issue_keyword,
            location=location,
            max_results=num_sources_per_location
        )

        if 'error' not in search_result:
            results = search_result['results']

            # Analyze source diversity
            diversity = analyze_source_diversity(results)

            location_data[location] = {
                'snippets': [r['content'] for r in results if r.get('content')],
                'sources': [{'title': r['title'], 'url': r['url'], 'domain': r['domain']}
                           for r in results],
                'diversity': diversity
            }

            log_tool_result_html(f"{location}: Found {len(results)} sources, diversity score: {diversity['diversity_score']}")

            # Show warnings
            if diversity['warnings']:
                for warning in diversity['warnings']:
                    log_warning_html(f"{location}: {warning}")
        else:
            log_warning_html(f"Failed to collect data for {location}: {search_result.get('error')}")

    summary = f"""
Collected data for {len(location_data)} location(s):
{chr(10).join([f"- {loc}: {len(data['snippets'])} snippets" for loc, data in location_data.items()])}
"""

    log_final_summary_html(summary)

    return {
        'issue': issue_keyword,
        'location_data': location_data,
        'collection_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }

print("✅ Geographic Listening Agent defined")

"""### 5.2. Comparative Sentiment Analysis Agent"""

# =========================
# Agent 2: Comparative Sentiment Analysis
# =========================

def comparative_sentiment_agent(listening_data: dict) -> dict:
    """
    Analyze sentiment separately for each location.
    """
    log_agent_title_html("Comparative Sentiment Analysis Agent", "🧠")

    issue = listening_data['issue']
    location_data = listening_data['location_data']

    location_sentiments = {}

    for location, data in location_data.items():
        snippets = data['snippets']

        if not snippets:
            log_warning_html(f"No data for {location}, skipping...")
            continue

        log_tool_call_html("analyze_sentiment_with_context", f"location={location}, samples={len(snippets)}")

        analyses = analyze_sentiment_with_context(snippets, issue)

        # Calculate statistics
        sentiments = [a.get('sentiment', 'neutral') for a in analyses if 'error' not in a]
        emotions = [a.get('emotion', 'neutral') for a in analyses if 'error' not in a]
        cultural_contexts = [a.get('cultural_context', 'Unknown') for a in analyses if 'error' not in a]
        all_themes = []
        for a in analyses:
            if 'themes' in a:
                all_themes.extend(a['themes'])

        sentiment_counts = Counter(sentiments)
        emotion_counts = Counter(emotions)
        theme_counts = Counter(all_themes)
        cultural_counts = Counter(cultural_contexts)

        total = len(sentiments) if sentiments else 1
        sentiment_dist = {
            'positive': (sentiment_counts.get('positive', 0) / total) * 100,
            'negative': (sentiment_counts.get('negative', 0) / total) * 100,
            'neutral': (sentiment_counts.get('neutral', 0) / total) * 100
        }

        # Credibility score (0-100)
        diversity_score = data['diversity']['diversity_score']
        sample_size_score = min(100, (len(snippets) / 20) * 100)
        credibility_score = (diversity_score * 0.6 + sample_size_score * 0.4)

        location_sentiments[location] = {
            'sentiment_distribution': sentiment_dist,
            'emotion_counts': dict(emotion_counts),
            'theme_counts': dict(theme_counts.most_common(10)),
            'cultural_contexts': dict(cultural_counts),
            'sample_size': len(sentiments),
            'credibility_score': round(credibility_score, 1),
            'diversity_metrics': data['diversity']
        }

        log_tool_result_html(
            f"{location}: Pos={sentiment_dist['positive']:.0f}% Neg={sentiment_dist['negative']:.0f}% "
            f"Neutral={sentiment_dist['neutral']:.0f}% | Credibility: {credibility_score:.0f}/100"
        )

    summary = f"""
Sentiment analysis complete for {len(location_sentiments)} location(s).

Regional Comparison:
{chr(10).join([f"- {loc}: {data['sentiment_distribution']['positive']:.0f}% positive, {data['sentiment_distribution']['negative']:.0f}% negative (n={data['sample_size']})"
               for loc, data in location_sentiments.items()])}
"""

    log_final_summary_html(summary)

    return {
        'issue': issue,
        'location_sentiments': location_sentiments
    }

print("✅ Comparative Sentiment Agent defined")

"""### 5.3. Comparative Visualization Designer Agent"""

# =========================
# Agent 3: Comparative Visualization Designer (Enhanced)
# =========================

def comparative_visualization_agent(sentiment_data: dict, listening_data: dict, output_dir: str = ".") -> dict:
    """
    Create side-by-side regional comparison visualizations with additional charts.
    """
    log_agent_title_html("Comparative Visualization Designer Agent", "📊")

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    chart_files = {}
    location_sentiments = sentiment_data['location_sentiments']

    # Chart 1: Regional Sentiment Comparison (Grouped Bar)
    log_tool_call_html("create_regional_comparison_chart")

    locations = list(location_sentiments.keys())
    positive_vals = [location_sentiments[loc]['sentiment_distribution']['positive'] for loc in locations]
    negative_vals = [location_sentiments[loc]['sentiment_distribution']['negative'] for loc in locations]
    neutral_vals = [location_sentiments[loc]['sentiment_distribution']['neutral'] for loc in locations]

    x = range(len(locations))
    width = 0.25

    fig, ax = plt.subplots(figsize=(12, 6))
    ax.bar([i - width for i in x], positive_vals, width, label='Positive', color='#10b981')
    ax.bar(x, negative_vals, width, label='Negative', color='#ef4444')
    ax.bar([i + width for i in x], neutral_vals, width, label='Neutral', color='#6b7280')

    ax.set_xlabel('Location', fontsize=12, fontweight='bold')
    ax.set_ylabel('Percentage (%)', fontsize=12, fontweight='bold')
    ax.set_title(f'Regional Sentiment Comparison: {sentiment_data["issue"]}', fontsize=14, fontweight='bold')
    ax.set_xticks(x)
    ax.set_xticklabels(locations, rotation=0)
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

    comparison_path = f'{output_dir}/regional_comparison_{timestamp}.png'
    plt.tight_layout()
    plt.savefig(comparison_path, dpi=150, bbox_inches='tight')
    plt.close()
    chart_files['regional_comparison'] = comparison_path
    log_tool_result_html(f"Saved to {comparison_path}")

    # Chart 2: Credibility Score Dashboard
    log_tool_call_html("create_credibility_dashboard")

    credibility_scores = [location_sentiments[loc]['credibility_score'] for loc in locations]
    sample_sizes = [location_sentiments[loc]['sample_size'] for loc in locations]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

    # Credibility scores
    colors = ['#10b981' if score >= 70 else '#f59e0b' if score >= 50 else '#ef4444'
              for score in credibility_scores]
    ax1.barh(locations, credibility_scores, color=colors)
    ax1.set_xlabel('Credibility Score (0-100)', fontsize=11)
    ax1.set_title('Data Credibility by Location', fontsize=13, fontweight='bold')
    ax1.axvline(x=70, color='green', linestyle='--', alpha=0.5, label='High (70+)')
    ax1.axvline(x=50, color='orange', linestyle='--', alpha=0.5, label='Medium (50-70)')
    ax1.legend(fontsize=9)
    ax1.grid(axis='x', alpha=0.3)

    # Sample sizes
    ax2.barh(locations, sample_sizes, color='#3b82f6')
    ax2.set_xlabel('Sample Size (n)', fontsize=11)
    ax2.set_title('Data Sample Sizes', fontsize=13, fontweight='bold')
    ax2.grid(axis='x', alpha=0.3)

    for i, v in enumerate(sample_sizes):
        ax2.text(v + 0.5, i, str(v), va='center', fontsize=10)

    credibility_path = f'{output_dir}/credibility_dashboard_{timestamp}.png'
    plt.tight_layout()
    plt.savefig(credibility_path, dpi=150, bbox_inches='tight')
    plt.close()
    chart_files['credibility_dashboard'] = credibility_path
    log_tool_result_html(f"Saved to {credibility_path}")

    # Chart 3: Source Diversity Comparison
    log_tool_call_html("create_source_diversity_chart")

    fig, ax = plt.subplots(figsize=(12, 6))

    for i, location in enumerate(locations):
        diversity_metrics = location_sentiments[location]['diversity_metrics']
        source_types = diversity_metrics.get('source_type_distribution', {})

        bottom = 0
        for source_type, count in source_types.items():
            ax.bar(i, count, bottom=bottom, label=source_type if i == 0 else "")
            bottom += count

    ax.set_xlabel('Location', fontsize=12, fontweight='bold')
    ax.set_ylabel('Number of Sources', fontsize=12, fontweight='bold')
    ax.set_title(f'Source Type Diversity: {sentiment_data["issue"]}', fontsize=14, fontweight='bold')
    ax.set_xticks(range(len(locations)))
    ax.set_xticklabels(locations)
    ax.legend(title='Source Type')
    ax.grid(axis='y', alpha=0.3)

    diversity_path = f'{output_dir}/source_diversity_{timestamp}.png'
    plt.tight_layout()
    plt.savefig(diversity_path, dpi=150, bbox_inches='tight')
    plt.close()
    chart_files['source_diversity'] = diversity_path
    log_tool_result_html(f"Saved to {diversity_path}")

    # Chart 4: Theme Frequency Bar Chart by Location (NEW)
    log_tool_call_html("create_theme_frequency_chart")

    # Collect top themes across all locations
    all_themes = set()
    for loc in locations:
        themes = list(location_sentiments[loc]['theme_counts'].keys())[:5]
        all_themes.update(themes)

    all_themes = list(all_themes)[:8]  # Limit to top 8 unique themes

    if all_themes:
        fig, ax = plt.subplots(figsize=(14, 7))

        x_pos = range(len(all_themes))
        bar_width = 0.8 / max(len(locations), 1)

        for i, location in enumerate(locations):
            theme_counts = location_sentiments[location]['theme_counts']
            theme_values = [theme_counts.get(theme, 0) for theme in all_themes]

            offset = (i - len(locations)/2) * bar_width + bar_width/2
            ax.bar([x + offset for x in x_pos], theme_values, bar_width,
                   label=location, alpha=0.8)

        ax.set_xlabel('Themes', fontsize=12, fontweight='bold')
        ax.set_ylabel('Frequency (mentions)', fontsize=12, fontweight='bold')
        ax.set_title(f'Theme Frequency Comparison: {sentiment_data["issue"]}',
                     fontsize=14, fontweight='bold')
        ax.set_xticks(x_pos)
        ax.set_xticklabels(all_themes, rotation=45, ha='right')
        ax.legend(title='Location', bbox_to_anchor=(1.05, 1), loc='upper left')
        ax.grid(axis='y', alpha=0.3)

        theme_freq_path = f'{output_dir}/theme_frequency_{timestamp}.png'
        plt.tight_layout()
        plt.savefig(theme_freq_path, dpi=150, bbox_inches='tight')
        plt.close()
        chart_files['theme_frequency'] = theme_freq_path
        log_tool_result_html(f"Saved to {theme_freq_path}")

    summary = f"""
Created {len(chart_files)} comparative visualizations:
1. Regional sentiment comparison (grouped bar chart)
2. Credibility score dashboard
3. Source diversity breakdown
4. Theme frequency comparison by location
"""

    log_final_summary_html(summary)

    return {
        'chart_files': chart_files,
        'issue': sentiment_data['issue']
    }

print("✅ Comparative Visualization Agent defined (Enhanced)")

"""### 5.4. Data Export Agent (CSV & Tables)"""

# =========================
# Agent 4: Data Export Agent
# =========================

def data_export_agent(listening_data: dict, sentiment_data: dict, output_dir: str = ".") -> dict:
    """
    Export all sentiment data to CSV files and generate data tables.

    Args:
        listening_data (dict): Raw listening data from geographic agent
        sentiment_data (dict): Processed sentiment data
        output_dir (str): Directory to save CSV files

    Returns:
        dict: CSV file paths and pandas DataFrames
    """
    log_agent_title_html("Data Export Agent", "💾")

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    location_sentiments = sentiment_data['location_sentiments']
    location_data = listening_data['location_data']

    csv_files = {}
    tables = {}

    # Table 1: Sentiment Distribution
    log_tool_call_html("create_sentiment_distribution_table")

    sentiment_rows = []
    for location, data in location_sentiments.items():
        sentiment_rows.append({
            'location': location,
            'positive_pct': round(data['sentiment_distribution']['positive'], 1),
            'negative_pct': round(data['sentiment_distribution']['negative'], 1),
            'neutral_pct': round(data['sentiment_distribution']['neutral'], 1),
            'sample_size': data['sample_size'],
            'credibility_score': data['credibility_score']
        })

    df_sentiment = pd.DataFrame(sentiment_rows)
    csv_path = f"{output_dir}/sentiment_distribution_{timestamp}.csv"
    df_sentiment.to_csv(csv_path, index=False)
    csv_files['sentiment_distribution'] = csv_path
    tables['sentiment_distribution'] = df_sentiment
    log_tool_result_html(f"Saved to {csv_path}")

    # Table 2: Emotion Frequency
    log_tool_call_html("create_emotion_frequency_table")

    # Get all unique emotions
    all_emotions = set()
    for data in location_sentiments.values():
        all_emotions.update(data['emotion_counts'].keys())

    emotion_rows = []
    for location, data in location_sentiments.items():
        row = {'location': location}
        for emotion in all_emotions:
            row[emotion] = data['emotion_counts'].get(emotion, 0)
        emotion_rows.append(row)

    df_emotions = pd.DataFrame(emotion_rows)
    csv_path = f"{output_dir}/emotion_frequency_{timestamp}.csv"
    df_emotions.to_csv(csv_path, index=False)
    csv_files['emotion_frequency'] = csv_path
    tables['emotion_frequency'] = df_emotions
    log_tool_result_html(f"Saved to {csv_path}")

    # Table 3: Theme Comparison
    log_tool_call_html("create_theme_comparison_table")

    # Get all unique themes
    all_themes = set()
    for data in location_sentiments.values():
        all_themes.update(data['theme_counts'].keys())

    all_themes = list(all_themes)[:15]  # Limit to top 15 themes

    theme_rows = []
    for location, data in location_sentiments.items():
        row = {'location': location}
        for theme in all_themes:
            row[theme] = data['theme_counts'].get(theme, 0)
        theme_rows.append(row)

    df_themes = pd.DataFrame(theme_rows)
    csv_path = f"{output_dir}/theme_comparison_{timestamp}.csv"
    df_themes.to_csv(csv_path, index=False)
    csv_files['theme_comparison'] = csv_path
    tables['theme_comparison'] = df_themes
    log_tool_result_html(f"Saved to {csv_path}")

    # Table 4: Source Attribution
    log_tool_call_html("create_source_attribution_table")

    source_rows = []
    for location, data in location_data.items():
        diversity = data['diversity']
        top_domains = diversity.get('top_domains', {})
        source_types = diversity.get('source_type_distribution', {})

        for domain, count in top_domains.items():
            # Classify source type
            if any(x in domain for x in ['reddit.com', 'twitter.com', 'facebook.com']):
                source_type = 'social_media'
            elif any(x in domain for x in ['news', 'times', 'post', 'bbc', 'cnn']):
                source_type = 'news'
            elif any(x in domain for x in ['.gov', '.edu']):
                source_type = 'institutional'
            else:
                source_type = 'other'

            source_rows.append({
                'location': location,
                'domain': domain,
                'source_type': source_type,
                'count': count
            })

    df_sources = pd.DataFrame(source_rows)
    csv_path = f"{output_dir}/source_attribution_{timestamp}.csv"
    df_sources.to_csv(csv_path, index=False)
    csv_files['source_attribution'] = csv_path
    tables['source_attribution'] = df_sources
    log_tool_result_html(f"Saved to {csv_path}")

    # Table 5: Credibility Metrics
    log_tool_call_html("create_credibility_metrics_table")

    credibility_rows = []
    for location, data in location_sentiments.items():
        diversity = data['diversity_metrics']
        credibility_rows.append({
            'location': location,
            'credibility_score': data['credibility_score'],
            'sample_size': data['sample_size'],
            'unique_domains': diversity['unique_domains'],
            'total_sources': diversity['total_sources'],
            'diversity_score': diversity['diversity_score'],
            'warnings': '; '.join(diversity.get('warnings', [])) if diversity.get('warnings') else 'None'
        })

    df_credibility = pd.DataFrame(credibility_rows)
    csv_path = f"{output_dir}/credibility_metrics_{timestamp}.csv"
    df_credibility.to_csv(csv_path, index=False)
    csv_files['credibility_metrics'] = csv_path
    tables['credibility_metrics'] = df_credibility
    log_tool_result_html(f"Saved to {csv_path}")

    summary = f"""
Exported 5 data tables to CSV files:
1. Sentiment distribution by location
2. Emotion frequency comparison
3. Theme comparison matrix
4. Source attribution breakdown
5. Credibility metrics detailed table

All CSV files can be opened in Excel or Google Sheets for further analysis.
"""

    log_final_summary_html(summary)

    return {
        'csv_files': csv_files,
        'tables': tables,
        'export_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }

print("✅ Data Export Agent defined")

"""### 5.5. Enhanced Packaging Agent with Credibility Report"""

# =========================
# Agent 5: Enhanced Packaging with Tables & Data Exports
# =========================

def enhanced_packaging_agent(
    listening_data: dict,
    sentiment_data: dict,
    visualization_data: dict,
    export_data: dict,
    output_path: str = None
) -> str:
    """
    Generate comparative report with credibility assessment and data tables.
    """
    log_agent_title_html("Enhanced Packaging Agent", "📝")

    issue = sentiment_data['issue']
    location_sentiments = sentiment_data['location_sentiments']
    chart_files = visualization_data.get('chart_files', {})
    tables = export_data.get('tables', {})
    csv_files = export_data.get('csv_files', {})

    # Generate executive summary
    log_tool_call_html("generate_comparative_summary")

    prompt = f"""
You are an intelligence analyst writing an executive summary comparing public sentiment across regions.

Issue: {issue}
Regional Data: {json.dumps({loc: data['sentiment_distribution'] for loc, data in location_sentiments.items()}, indent=2)}

Write 3-4 sentences highlighting:
1. Key regional differences
2. Most striking contrasts
3. Potential cultural/geographic factors
"""

    try:
        response = model.generate_content(prompt)
        executive_summary = response.text.strip()
    except:
        executive_summary = "Regional sentiment analysis reveals significant geographic variation in public opinion."

    log_tool_result_html(executive_summary[:150] + "...")

    # Build markdown report with tables
    markdown_content = f"""# 🌍 Comparative Public Sentiment Intelligence Report

**Issue Analyzed:** {issue}
**Analysis Date:** {listening_data['collection_date']}
**Locations:** {', '.join(location_sentiments.keys())}
**Total Samples:** {sum(data['sample_size'] for data in location_sentiments.values())}

---

## 📊 Executive Summary

{executive_summary}

---

## 🌐 Regional Sentiment Comparison

![Regional Comparison]({chart_files.get('regional_comparison', '')})

### Sentiment Distribution Table

"""

    # Add Sentiment Distribution Table
    if 'sentiment_distribution' in tables:
        markdown_content += tables['sentiment_distribution'].to_markdown(index=False) + "\n\n"

    markdown_content += "### Detailed Breakdown by Location\n\n"

    for location, data in location_sentiments.items():
        sentiment_dist = data['sentiment_distribution']
        credibility = data['credibility_score']
        sample_size = data['sample_size']

        # Credibility indicator
        if credibility >= 70:
            credibility_badge = "🟢 HIGH"
        elif credibility >= 50:
            credibility_badge = "🟡 MEDIUM"
        else:
            credibility_badge = "🔴 LOW"

        markdown_content += f"""
#### {location}

**Credibility:** {credibility_badge} ({credibility:.0f}/100) | **Sample Size:** {sample_size}

| Sentiment | Percentage |
|-----------|------------|
| ✅ Positive | {sentiment_dist['positive']:.1f}% |
| ❌ Negative | {sentiment_dist['negative']:.1f}% |
| ⚪ Neutral | {sentiment_dist['neutral']:.1f}% |

**Top Emotions:** {', '.join([f"{e} ({c})" for e, c in list(data['emotion_counts'].items())[:3]])}

**Key Themes:** {', '.join(list(data['theme_counts'].keys())[:5])}

"""

        # Add warnings if credibility is low
        warnings = data['diversity_metrics'].get('warnings', [])
        if warnings:
            markdown_content += "\n**⚠️ Data Quality Warnings:**\n"
            for warning in warnings:
                markdown_content += f"- {warning}\n"

        markdown_content += "\n---\n\n"

    # Add Emotion Frequency Table
    markdown_content += f"""
## 😊 Emotion Frequency Comparison

![Emotion Breakdown]({chart_files.get('emotion_bar', '')})

### Emotion Frequency Table

"""

    if 'emotion_frequency' in tables:
        markdown_content += tables['emotion_frequency'].to_markdown(index=False) + "\n\n"
        markdown_content += f"**CSV Export:** `{os.path.basename(csv_files.get('emotion_frequency', ''))}`\n\n"

    markdown_content += "---\n\n"

    # Add Theme Frequency Chart and Table
    markdown_content += f"""
## 💡 Theme Frequency Comparison

![Theme Frequency]({chart_files.get('theme_frequency', '')})

### Theme Comparison Matrix

"""

    if 'theme_comparison' in tables:
        # Show transposed version for better readability (themes as rows)
        df_themes_display = tables['theme_comparison'].set_index('location').T
        markdown_content += df_themes_display.to_markdown() + "\n\n"
        markdown_content += f"**CSV Export:** `{os.path.basename(csv_files.get('theme_comparison', ''))}`\n\n"

    markdown_content += "---\n\n"

    # Add Credibility Assessment
    markdown_content += f"""
## 🔍 Data Credibility Assessment

![Credibility Dashboard]({chart_files.get('credibility_dashboard', '')})

### Credibility Metrics Table

"""

    if 'credibility_metrics' in tables:
        markdown_content += tables['credibility_metrics'].to_markdown(index=False) + "\n\n"
        markdown_content += f"**CSV Export:** `{os.path.basename(csv_files.get('credibility_metrics', ''))}`\n\n"

    markdown_content += f"""

### Credibility Scoring Methodology

Each location's data is scored on:
1. **Source Diversity (60%)** - Variety of domains and source types
2. **Sample Size (40%)** - Number of data points analyzed

**Score Interpretation:**
- 🟢 **70-100:** High confidence - Diverse sources, adequate sample
- 🟡 **50-69:** Medium confidence - Some limitations present
- 🔴 **0-49:** Low confidence - Significant data quality concerns

---

## 📚 Source Diversity Analysis

![Source Diversity]({chart_files.get('source_diversity', '')})

### Source Attribution Table

"""

    if 'source_attribution' in tables:
        # Group by location and show top 3 domains per location
        for location in location_sentiments.keys():
            location_sources = tables['source_attribution'][tables['source_attribution']['location'] == location]
            if not location_sources.empty:
                markdown_content += f"\n**{location}:**\n\n"
                markdown_content += location_sources.head(5).to_markdown(index=False) + "\n"

        markdown_content += f"\n\n**Full CSV Export:** `{os.path.basename(csv_files.get('source_attribution', ''))}`\n\n"

    markdown_content += f"""

---

## 📁 Data Exports

All analysis data has been exported to CSV files for further analysis:

1. **Sentiment Distribution:** `{os.path.basename(csv_files.get('sentiment_distribution', ''))}`
2. **Emotion Frequency:** `{os.path.basename(csv_files.get('emotion_frequency', ''))}`
3. **Theme Comparison:** `{os.path.basename(csv_files.get('theme_comparison', ''))}`
4. **Source Attribution:** `{os.path.basename(csv_files.get('source_attribution', ''))}`
5. **Credibility Metrics:** `{os.path.basename(csv_files.get('credibility_metrics', ''))}`

These CSV files can be opened in Excel, Google Sheets, or any data analysis tool.

---

## ⚠️ Limitations & Disclaimers

### Data Collection Limitations

1. **Language Bias:** Primarily English-language sources (non-English opinions underrepresented)
2. **Digital Divide:** Only captures online populations (offline communities excluded)
3. **Platform Bias:** Web search favors certain platforms over others
4. **Temporal:** Snapshot in time, sentiment may shift rapidly
5. **Sample Size:** Small samples may not represent entire populations

### Geographic Filtering Challenges

- Geographic attribution is **approximate** (based on search query modifiers)
- Cross-border content may appear in multiple regions
- VPNs and global platforms complicate true location detection

### Recommended Use

✅ **Good for:** Directional insights, trend detection, hypothesis generation
⚠️ **Caution for:** Policy decisions, legal proceedings, precise measurement
❌ **Not for:** Statistical inference about entire populations

---

## 🎯 Recommendations

Based on regional variation observed:

1. **Localize messaging** - Tailor communications to regional sentiment patterns
2. **Address regional concerns** - Focus on location-specific themes
3. **Monitor low-confidence regions** - Collect additional data where credibility is weak
4. **Validate with additional methods** - Complement with surveys, focus groups, etc.

---

*Report generated by Public Sentiment Collection Workflow (Enhanced v1)*
*Powered by Google Gemini 2.5 Flash & Tavily Geographic Search*
"""

    if output_path is None:
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        output_path = f"comparative_sentiment_report_{timestamp}.md"

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(markdown_content)

    summary = f"""
Enhanced comparative report generated!

Report includes:
- Regional sentiment comparison charts
- Sentiment distribution table
- Emotion frequency table
- Theme comparison matrix
- Credibility metrics table
- Source attribution breakdown
- 5 CSV exports for further analysis
- Data quality warnings
- Methodological limitations
- Actionable recommendations

Saved to: {output_path}
"""

    log_final_summary_html(summary)

    return output_path

print("✅ Enhanced Packaging Agent defined")

"""## 6. Pipeline Function

This is the main orchestration function that runs all 5 agents in sequence.
"""

# =========================
# Enhanced Pipeline (5 Stages)
# =========================

def run_enhanced_sentiment_pipeline(
    issue_keyword: str,
    locations: list = ["global"],
    num_sources_per_location: int = 15,
    output_dir: str = "."
) -> dict:
    """
    Run enhanced pipeline with geographic segmentation, credibility tracking, and data exports.

    Args:
        issue_keyword (str): Topic to analyze
        locations (list): Regions to compare (e.g., ["USA", "Germany", "Saudi Arabia"])
        num_sources_per_location (int): Sources per location
        output_dir (str): Output directory

    Returns:
        dict: Complete results with credibility metrics, charts, and CSV exports
    """
    print("\n" + "="*70)
    print("🚀 ENHANCED PUBLIC SENTIMENT ANALYSIS PIPELINE")
    print("="*70 + "\n")

    # Stage 1: Geographic Listening
    listening_data = geographic_listening_agent(
        issue_keyword,
        locations,
        num_sources_per_location
    )
    print("\n✅ Stage 1/5 Complete: Geographic Social Listening\n")

    # Stage 2: Comparative Sentiment Analysis
    sentiment_data = comparative_sentiment_agent(listening_data)
    print("\n✅ Stage 2/5 Complete: Comparative Sentiment Analysis\n")

    # Stage 3: Comparative Visualization (with theme frequency chart)
    visualization_data = comparative_visualization_agent(sentiment_data, listening_data, output_dir)
    print("\n✅ Stage 3/5 Complete: Comparative Visualization\n")

    # Stage 4: Data Export (CSV files and tables)
    export_data = data_export_agent(listening_data, sentiment_data, output_dir)
    print("\n✅ Stage 4/5 Complete: Data Export\n")

    # Stage 5: Enhanced Packaging (with all tables)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    report_path = enhanced_packaging_agent(
        listening_data,
        sentiment_data,
        visualization_data,
        export_data,
        output_path=f"{output_dir}/comparative_report_{timestamp}.md"
    )
    print("\n✅ Stage 5/5 Complete: Enhanced Packaging\n")

    print("\n" + "="*70)
    print("🎉 ENHANCED PIPELINE COMPLETE!")
    print("="*70)
    print(f"\n📄 Report: {report_path}")
    print(f"📊 Charts: {len(visualization_data['chart_files'])} PNG files")
    print(f"💾 CSV Exports: {len(export_data['csv_files'])} files")
    print(f"🌍 Locations analyzed: {len(locations)}\n")

    return {
        'listening_data': listening_data,
        'sentiment_data': sentiment_data,
        'visualization_data': visualization_data,
        'export_data': export_data,
        'report_path': report_path
    }

print("✅ Enhanced pipeline function defined (5 stages with data exports)")

"""## 7. Verification Cell

Run this cell before executing the pipeline to ensure all agents are properly defined.
"""

# Verification: Check if all required functions are defined
required_functions = [
    'geographic_listening_agent',
    'comparative_sentiment_agent',
    'comparative_visualization_agent',
    'data_export_agent',
    'enhanced_packaging_agent'
]

missing = []
for func_name in required_functions:
    if func_name not in globals():
        missing.append(func_name)

if missing:
    print("❌ ERROR: The following functions are not defined:")
    for func in missing:
        print(f"   - {func}")
    print("\n⚠️ Please run ALL cells above in sequence before running the pipeline!")
else:
    print("✅ All required functions are defined. Ready to run pipeline!")

"""## 8. Example Usage

### Example 1: Alcohol Consumption Analysis
"""

# Example: Analyze alcohol consumption sentiment across cultures
results = run_enhanced_sentiment_pipeline(
    issue_keyword="Should firecrackers and fireworks be banned?",
    locations=["Malaysia", "Germany", "USA", "India"],
    num_sources_per_location=15,
    output_dir="."
)

"""### View Results"""

# Display exported tables
tables = results['export_data']['tables']

print("="*70)
print("SENTIMENT DISTRIBUTION TABLE")
print("="*70)
display(tables['sentiment_distribution'])

print("\n" + "="*70)
print("EMOTION FREQUENCY TABLE")
print("="*70)
display(tables['emotion_frequency'])

print("\n" + "="*70)
print("THEME COMPARISON MATRIX")
print("="*70)
display(tables['theme_comparison'])

print("\n" + "="*70)
print("CREDIBILITY METRICS TABLE")
print("="*70)
display(tables['credibility_metrics'])

print("\n" + "="*70)
print("SOURCE ATTRIBUTION TABLE (Top 10)")
print("="*70)
display(tables['source_attribution'].head(10))

"""### View Credibility Assessment"""

# View credibility scores and warnings
print("\n=== CREDIBILITY ASSESSMENT ===")
for location, data in results['sentiment_data']['location_sentiments'].items():
    print(f"\n{location}:")
    print(f"  Credibility Score: {data['credibility_score']}/100")
    print(f"  Sample Size: {data['sample_size']}")
    print(f"  Unique Sources: {data['diversity_metrics']['unique_domains']}")
    print(f"  Source Types: {data['diversity_metrics']['source_type_distribution']}")

    if data['diversity_metrics']['warnings']:
        print("  ⚠️ Warnings:")
        for warning in data['diversity_metrics']['warnings']:
            print(f"    - {warning}")

print("\n=== EXPORTED CSV FILES ===")
for file_type, file_path in results['export_data']['csv_files'].items():
    print(f"{file_type}: {file_path}")



"""## 9. Summary

### ✅ Complete Feature List:

1. **🌍 Geographic Segmentation** - Analyze sentiment by region/country
2. **📊 Credibility Scoring** - 0-100 score based on diversity and sample size
3. **⚠️ Bias Detection** - Automatic warnings for data quality issues
4. **📈 4 Visualizations** - Regional comparison, credibility dashboard, source diversity, theme frequency
5. **💾 5 CSV Exports** - All data exported for Excel/Google Sheets
6. **📝 Comprehensive Report** - Markdown report with embedded tables and charts

### 📦 Output Package:

**Total: 10 files per analysis**
- 1 Markdown report
- 4 PNG charts
- 5 CSV data files

### 🎓 Educational Value:

Students learn:
- Sampling bias in sentiment analysis
- Geographic filtering techniques
- Data credibility assessment
- Multi-agent AI architecture
- Professional data presentation

---

**Version:** Enhanced v1 (Clean)  
**Date:** 2025-10-21  
**Status:** Production-ready

# Task
Generate a PDF report from the markdown findings.

## Install pdf generation library

### Subtask:
Install a Python library that can convert markdown or HTML to PDF.

**Reasoning**:
The subtask requires installing a Python library to convert markdown or HTML to PDF. `weasyprint` is specified as a suitable library for this purpose and can be installed using pip.
"""

!pip install -q weasyprint

"""## Generate pdf from markdown

### Subtask:
Use the generated markdown report and the installed library to create a PDF file.

**Reasoning**:
The first step is to read the markdown report into a string.
"""

report_path = results['report_path']
with open(report_path, 'r', encoding='utf-8') as f:
    markdown_content = f.read()

print("✅ Markdown report read successfully")

"""**Reasoning**:
Now that the markdown content is read, I need to convert it to HTML and then generate the PDF using `weasyprint`. Since `weasyprint` works with HTML and CSS, I will use the `markdown` library to convert the markdown to HTML first. Then I will use `weasyprint` to generate the PDF.


"""

import markdown
from weasyprint import HTML, CSS
import os

# Convert markdown to HTML
html_content = markdown.markdown(markdown_content)

# Define the output PDF path
pdf_path = report_path.replace('.md', '.pdf')

# Create HTML object from HTML content
html = HTML(string=html_content)

# Generate PDF
html.write_pdf(pdf_path)

print(f"✅ PDF report generated successfully at: {pdf_path}")

"""## Confirm pdf creation

### Subtask:
Verify that the PDF file has been successfully created.

**Reasoning**:
Verify that the PDF file exists at the specified path.
"""

import os

if os.path.exists(pdf_path):
    print(f"✅ PDF file verified: {pdf_path}")
else:
    print(f"❌ PDF file not found at: {pdf_path}")

"""## Summary:

### Data Analysis Key Findings

* The `weasyprint` library was successfully installed for converting HTML/CSS to PDF.
* The markdown content was successfully read from the report file.
* The markdown content was converted to HTML using the `markdown` library.
* A PDF report was successfully generated from the HTML content using `weasyprint` and saved to the specified path.
* Errors regarding "Relative URI reference without a base URI" were encountered during PDF generation, indicating potential issues with image inclusion.
* The existence of the generated PDF file was successfully verified.

### Insights or Next Steps

* Investigate and resolve the "Relative URI reference without a base URI" errors to ensure all images are included in the PDF report.
* Review the generated PDF to confirm formatting and content accuracy.

"""