"""Build bloom-house.db (SQLite) and emit data/db.js with the DB embedded as base64.

The governed toolset runs FIXED, parameterized queries against this DB in the browser
via sql.js. Embedding as base64 means the page also runs from file:// (no fetch needed).
Only 3 SKUs get a live product page (the two birthday picks + the condolence stand);
the rest carry an empty url and render as a demo affordance.
"""
import sqlite3, base64, os

HERE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(HERE, "bloom-house.db")
JS_DIR = os.path.join(HERE, "data")
JS_PATH = os.path.join(JS_DIR, "db.js")

# occasions stored comma-wrapped (",a,b,") so LIKE '%,occ,%' matches whole tokens only
def occ(*tags):
    return "," + ",".join(tags) + ","

PRODUCTS = [
    # id, name, flower, colour, price, occasions, url
    ("rose-classic", "Classic Red Rose Bouquet",        "rose",      "red",    135, occ("anniversary","love","apology"),          ""),
    ("carn-pink",    "Pink Carnation Bouquet",          "carnation", "pink",   145, occ("thank-you","birthday","friendship"),      ""),
    ("rose-ruby",    "Ruby Rose Bouquet",               "rose",      "red",    159, occ("anniversary","love"),                     ""),
    ("lily-pink",    "Pink Lily Bouquet",               "lily",      "pink",   169, occ("get-well","thank-you","birthday"),        "products/lily-pink.html"),
    ("tulip-box",    "Sunshine Tulip Flower Box",       "tulip",     "orange", 169, occ("birthday","congrats","get-well"),         ""),
    ("peony-box",    "Pink Peony Flower Box",           "peony",     "pink",   189, occ("birthday","congrats","just-because"),     "products/peony-box.html"),
    ("hydra-pink",   "Pink Hydrangea Bouquet",          "hydrangea", "pink",   229, occ("birthday","congrats"),                    ""),
    ("cond-stand",   "Serene Condolence Flower Stand",  "lily",      "white",  239, occ("condolence"),                             "products/cond-stand.html"),
]

ORDERS = [
    # order_no, status, eta
    ("BC10432", "out for delivery", "today before 5 PM"),
    ("BC10500", "being prepared",   "today between 2 and 5 PM"),
    ("BC10288", "delivered",        "yesterday at 3:14 PM"),
]

if os.path.exists(DB_PATH):
    os.remove(DB_PATH)
os.makedirs(JS_DIR, exist_ok=True)

con = sqlite3.connect(DB_PATH)
cur = con.cursor()
cur.execute("""CREATE TABLE products(
    id TEXT PRIMARY KEY, name TEXT, flower TEXT, colour TEXT,
    price INTEGER, occasions TEXT, url TEXT)""")
cur.execute("""CREATE TABLE orders(
    order_no TEXT PRIMARY KEY, status TEXT, eta TEXT)""")
cur.executemany("INSERT INTO products VALUES (?,?,?,?,?,?,?)", PRODUCTS)
cur.executemany("INSERT INTO orders VALUES (?,?,?)", ORDERS)
con.commit()
con.close()

with open(DB_PATH, "rb") as f:
    b64 = base64.b64encode(f.read()).decode("ascii")

with open(JS_PATH, "w", encoding="utf-8") as f:
    f.write("/* AUTO-GENERATED by build_db.py — do not edit by hand. */\n")
    f.write("/* bloom-house.db (SQLite) embedded as base64 so the governed */\n")
    f.write("/* toolset runs real fixed queries in-browser, even from file://. */\n")
    f.write('window.BLOOM_DB_B64 = "' + b64 + '";\n')

print("OK  products:", len(PRODUCTS), " orders:", len(ORDERS))
print("OK  db bytes:", os.path.getsize(DB_PATH), " base64 chars:", len(b64))
print("OK  wrote:", JS_PATH)
