[build]
  # No build process needed for static files
  publish = "."
  
[build.environment]
  # No environment variables needed for static site
  
[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  # CORS headers for API requests
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[redirects]]
  # SPA fallback
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
  
# File-based routing
[[redirects]]
  from = "/api/*"
  to = "https://claude-pdf-summarizer-wmpytqcfsa-uc.a.run.app/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404