"""
Build the frontend data bundle.

One card per question. Each card has to stand on its own, so everything it
needs is computed here per question and nothing is aggregated:

  what it said     the approved reply
  where from       the exact passage from the kitchen's document, plus the
                   whole document so a reader can check the quote in context
  how fast         measured time for retrieval to find that document
  how it reads     four or five warmth checks, answered in code, each one
                   stated in plain words and verifiable by reading the reply

The reply text is the kitchen's approved wording. It is not generated by the
model on this run, because the free tier caps generation at 20 requests per day
per model. The retrieval and the timings are real.
"""

import html
import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).parent
SOURCE_HTML = ROOT / "fixed_question_and_answer_warm.html"
OUT = ROOT / "bundle.json"

# Question 37 is dropped: no document covers 9 August, a Sunday.
DROP = {"Q37"}

# Q32's reply was curated from the FAQ row, but the binding statement lives in
# the delivery policy, and that is what retrieval returns. Point at the source
# that actually carries the rule.
RELABEL = {"Q32": "delivery_policy#s02"}

# Questions that no document can answer, because the answer lives in the
# subscription records and differs per customer. These run through the governed
# tools: the assistant picks which of six approved questions to ask, and never
# writes a query, sees the schema, or reaches another customer's record.
#
# The reply text is a template filled from the tool result, so the number in the
# sentence cannot drift from the number in the database.
DEMO_CUSTOMER = "Lim J.S."

RECORD_QUESTIONS = [
    {
        "id": "R1",
        "question": "How many meals do I have left?",
        "tool": "get_meals_remaining",
        "template": "You have {meals_remaining} lunches left, out of the "
                    "{meals_purchased} in your current cycle.",
        "show": ["plan_type", "service", "start_date", "meals_purchased",
                 "meals_delivered", "meals_remaining", "status"],
    },
    {
        "id": "R2",
        "question": "When does my cycle end?",
        "tool": "get_cycle_end_date",
        "template": "Your cycle ends on {cycle_end_pretty}, a little later than "
                    "usual because {holidays_in_cycle} public holidays fell inside it.",
        "show": ["start_date", "service_days", "holidays_in_cycle", "cycle_end_date"],
    },
]

DOC_TITLES = {
    "faq": "Frequently Asked Questions",
    "delivery_policy": "Delivery Policy",
    "subscription_guide": "Subscription Guide",
    "payment_and_refund_policy": "Payment and Refund Policy",
    "business_info": "Business Information",
    "addons_and_soups": "Add-on Menu and Soups",
    "holiday_notice_2026": "Public Holiday Notice",
    "menu_week_1": "Week 1 Menu", "menu_week_2": "Week 2 Menu",
    "menu_week_3": "Week 3 Menu", "menu_week_4": "Week 4 Menu",
}

# ---------------------------------------------------------------- warmth
# Each check is a plain sentence shown on the card, so a reader can disagree
# by looking at the reply. No model involved, no score, no aggregate.

DECLINE = re.compile(
    r"\b(sorry|we don't|we do not|aren't able|are not able|no longer able|"
    r"there's no|there is no|we can't|we cannot|we don't have)\b", re.I)

REASON_OR_WAY_FORWARD = re.compile(
    r"\b(because|since|once|so|as everything|only to|only deliver|"
    r"but you can|but if|instead|next time|we'd be happy|we hope|"
    r"you can choose|whichever)\b", re.I)

REDIRECT = re.compile(r"\bsee [a-z_]+_|check the menu|refer to\b", re.I)
SPEAKS = re.compile(r"\b(you|your|you'?ll|you'?d|we|us|our|we'?re|we'?d|we'?ll)\b", re.I)


def sentences(text):
    return [s for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s]


def warmth_checks(answer):
    declines = bool(DECLINE.search(answer))
    checks = [
        {"label": "Speaks to you directly, the way a person would",
         "pass": bool(SPEAKS.search(answer))},
        # a verdict is a reply that is NOTHING BUT "No" or "Yes". An opener
        # like "Yes! You can start whenever you're ready" is warm, not a verdict.
        {"label": "Reads as a sentence, not a one-word verdict",
         "pass": re.sub(r"[^a-z]", "", answer.lower()) not in ("no", "yes")},
        {"label": "Short enough to read at a glance",
         "pass": len(sentences(answer)) <= 2},
        {"label": "Answers you here, without sending you off to read a document",
         "pass": not bool(REDIRECT.search(answer))},
    ]
    if declines:
        checks.append({
            "label": "Gives a reason or a way forward, not just a no",
            "pass": bool(REASON_OR_WAY_FORWARD.search(answer)),
        })
    return declines, checks


# ---------------------------------------------------------------- sources
def load_corpus():
    """Every document, frontmatter stripped, for the read-in-full panel."""
    docs = {}
    for f in sorted((ROOT / "corpus").glob("*.md")):
        raw = f.read_text(encoding="utf-8")
        body = raw.split("---", 2)[2] if raw.startswith("---") else raw
        docs[f.stem] = body.strip()
    return docs


def quote_from(chunk_text):
    """
    The passage as the document states it.

    Two things are removed, neither of which is document prose:
      the chunker's own header line ("Delivery Policy, Service days.")
      the FAQ's question heading, since the card already shows the question

    One thing is rewritten: a document id written inside the text, such as
    "See delivery_policy", is shown under the document's real title. Same
    sentence, readable by someone who has never seen a file name.
    """
    t = chunk_text
    if "Answer:" in t:                              # FAQ chunk: keep the answer
        t = t.split("Answer:", 1)[1]
    else:
        t = re.sub(r"^[^\n]*\.\n\n", "", t)         # drop the chunker's header
        t = re.sub(r"^#+ .*\n", "", t, flags=re.M)  # drop markdown headings
    t = " ".join(t.split())
    for doc_id in sorted(DOC_TITLES, key=len, reverse=True):
        if "_" in doc_id:                           # never touch a bare word
            t = re.sub(r"\b" + re.escape(doc_id) + r"\b", DOC_TITLES[doc_id], t)
    return t


def load_approved():
    t = SOURCE_HTML.read_text(encoding="utf-8")
    groups = re.findall(
        r'<h2>(.*?) <span class="gc">\d+</span></h2>'
        r'<p class="gid">(.*?)</p>'
        r'<div class="rows">(.*?)</div></section>', t, re.S)
    rows = []
    for label, _doc, block in groups:
        for num, q, a, chunk in re.findall(
                r'<b class="num">(\d+)</b><span class="q">(.*?)</span>.*?'
                r'<p class="new">(.*?)</p>.*?<code>(.*?)</code>', block, re.S):
            qid = "Q" + num
            if qid in DROP:
                continue
            rows.append({
                "id": qid,
                "group": html.unescape(label),
                "question": html.unescape(re.sub(r"<[^>]+>", "", q)).strip(),
                "answer": html.unescape(re.sub(r"<[^>]+>", "", a)).strip(),
                "source_chunk": RELABEL.get(qid, html.unescape(chunk).strip()),
            })
    return rows


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    rows = load_approved()
    # renumber 1..N in reading order. The old numbers were positions in the
    # 35 question review sheet and carry gaps that mean nothing to a reader.
    for n, r in enumerate(rows, 1):
        r["n"] = n
    corpus = load_corpus()
    chunks = {c["chunk_id"]: c for c in
              json.loads((ROOT / "chunks.json").read_text(encoding="utf-8"))}
    print(f"questions: {len(rows)}")

    from rag.retriever import retrieve
    retrieve("warm up the cross encoder")

    for i, r in enumerate(rows, 1):
        doc = r["source_chunk"].split("#")[0]
        r["doc_id"] = doc
        r["doc_title"] = DOC_TITLES.get(doc, doc)
        r["quote"] = quote_from(chunks[r["source_chunk"]]["text"])

        t0 = time.perf_counter()
        hits = retrieve(r["question"])
        r["ms"] = int((time.perf_counter() - t0) * 1000)
        r["found"] = doc in [h.doc_id for h in hits]

        r["declines"], r["checks"] = warmth_checks(r["answer"])
        flag = "" if r["found"] else "   NOT FOUND"
        print(f"  {i:2}/{len(rows)}  {r['ms']:4} ms  {r['question'][:52]}{flag}")

    # ---- record questions, answered from the database, not the documents ----
    from datetime import date
    import rag.tools as tools

    for spec in RECORD_QUESTIONS:
        t0 = time.perf_counter()
        result = getattr(tools, spec["tool"])(DEMO_CUSTOMER)
        ms = (time.perf_counter() - t0) * 1000

        if "cycle_end_date" in result:
            y, m, d = (int(x) for x in result["cycle_end_date"].split("-"))
            result["cycle_end_pretty"] = date(y, m, d).strftime("%A %-d %B") \
                if sys.platform != "win32" else date(y, m, d).strftime("%A %#d %B")

        answer = spec["template"].format(**result)
        declines, checks = warmth_checks(answer)
        rows.append({
            "id": spec["id"], "n": len(rows) + 1,
            "group": "Your subscription records",
            "kind": "record",
            "question": spec["question"],
            "answer": answer,
            "tool": spec["tool"],
            "customer": result.get("name", DEMO_CUSTOMER),
            "record": [{"field": k.replace("_", " "), "value": str(result[k])}
                       for k in spec["show"] if k in result],
            "ms": round(ms, 1),
            "found": True,
            "declines": declines, "checks": checks,
        })
        print(f"  {spec['id']}   {ms:6.1f} ms  {spec['question']}   [{spec['tool']}]")

    for r in rows:
        r.setdefault("kind", "document")

    failed = [c["label"] for r in rows for c in r["checks"] if not c["pass"]]
    notfound = [r["id"] for r in rows if not r["found"]]

    bundle = {
        "answer_source": "approved",
        "documents": corpus,
        "doc_titles": DOC_TITLES,
        "questions": rows,
    }
    OUT.write_text(json.dumps(bundle, ensure_ascii=False, indent=1), encoding="utf-8")

    print(f"\nwarmth checks not passing: {len(failed)}")
    for f in set(failed):
        print("   ", f, "x", failed.count(f))
    print(f"source document not found : {notfound or 'none'}")
    print(f"written: {OUT.name}, {OUT.stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    main()
