"""
build_full_data.py  (keyless, network-free)

Reads the full Kaggle vehicle-fraud dataset and emits a compact, dictionary-encoded
asset holding ALL 15,420 claims, plus a meta file. The browser decodes it and applies
the FIXED yardstick (a deterministic rule, no model), so every claim classifies into
one of the four categories the same way, every time.

  data/claims-full.js  ->  window.MC = { fields, legend, rows, fraud }
  data/meta.json       ->  population provenance + per-category counts

Encoding: each field's distinct values are listed once in `legend`; each claim row is a
list of small integer indices into those legends. `fraud` is a parallel 0/1 array
(ground truth, read only after classification, never an input to the rule).
"""

import json
import os
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "dataset.csv")
OUT_DIR = os.path.join(HERE, "data")

# columns kept (clean snake_case) -> the 7 yardstick drivers + display context
COLS = {
    "Make": "make", "VehicleCategory": "vehicle_category", "AccidentArea": "accident_area",
    "Fault": "fault", "BasePolicy": "base_policy", "PolicyType": "policy_type",
    "VehiclePrice": "vehicle_price", "AgeOfVehicle": "age_of_vehicle",
    "AgeOfPolicyHolder": "age_of_policy_holder", "Days_Policy_Accident": "days_policy_accident",
    "Days_Policy_Claim": "days_policy_claim", "PastNumberOfClaims": "past_number_of_claims",
    "PoliceReportFiled": "police_report_filed", "WitnessPresent": "witness_present",
    "AddressChange_Claim": "address_change_claim",
}


def yardstick(row):
    """The fixed rule. Returns (risk_points, category). Pure function of the fields."""
    s = 0
    if row["fault"] == "Policy Holder":
        s += 2
    if row["base_policy"] == "All Perils":
        s += 2
    elif row["base_policy"] == "Collision":
        s += 1
    if row["address_change_claim"] in ("under 6 months", "2 to 3 years"):
        s += 2
    if row["days_policy_accident"] == "none":
        s += 2
    if row["accident_area"] == "Rural":
        s += 1
    if row["vehicle_price"] in ("less than 20000", "more than 69000"):
        s += 1
    if row["age_of_vehicle"] in ("new", "3 years", "4 years"):
        s += 1
    cat = "Fast track" if s <= 2 else "Approve" if s == 3 else "Investigate" if s <= 5 else "Repudiate"
    return s, cat


def main():
    df = pd.read_csv(SRC)[list(COLS)].rename(columns=COLS).fillna("").astype(str)
    fields = list(COLS.values())

    legend = {f: sorted(df[f].unique().tolist()) for f in fields}
    index = {f: {v: i for i, v in enumerate(legend[f])} for f in fields}
    rows = [[index[f][r[f]] for f in fields] for _, r in df.iterrows()]

    fraud = pd.read_csv(SRC)["FraudFound_P"].astype(int).tolist()

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "claims-full.js"), "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_full_data.py. All real Kaggle claims, dictionary-encoded.\n")
        f.write("// Decode in the browser; the fixed yardstick classifies each claim deterministically.\n")
        f.write("window.MC = ")
        json.dump({"fields": fields, "legend": legend, "rows": rows, "fraud": fraud}, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    # category counts (for the meta + a sanity check)
    cats = {"Fast track": [0, 0], "Approve": [0, 0], "Investigate": [0, 0], "Repudiate": [0, 0]}
    for (_, r), fr in zip(df.iterrows(), fraud):
        _, c = yardstick(r)
        cats[c][0] += 1
        cats[c][1] += fr

    meta = {
        "source": "Kaggle Vehicle Insurance Fraud Detection (fraud_oracle)",
        "total_claims": len(df),
        "total_fraud": sum(fraud),
        "true_fraud_rate": round(sum(fraud) / len(df), 4),
        "categories": {k: {"claims": v[0], "fraud": v[1], "fraud_rate": round(v[1] / v[0], 4)} for k, v in cats.items()},
        "note": "Full population, no rebalancing. Classification is a fixed deterministic yardstick over the fields; the fraud label is used only to score the flags.",
    }
    with open(os.path.join(OUT_DIR, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)

    kb = os.path.getsize(os.path.join(OUT_DIR, "claims-full.js")) // 1024
    print("Wrote data/claims-full.js ({} claims, {} KB) + data/meta.json".format(len(rows), kb))
    for k, v in cats.items():
        print("  {:12} {:5d} claims  {:.1%} fraud".format(k, v[0], v[1] / v[0]))


if __name__ == "__main__":
    main()
