"""
prep_data.py  (keyless, network-free)

Reads the real Kaggle "Vehicle Insurance Fraud Detection" file (dataset.csv),
draws a stratified demo sample of 150 real claims (40 fraud / 110 legitimate),
maps the bucketed columns into the claim shape the UI consumes, and writes:

  data/claims.js   ->  window.CLAIMS = [ {id, display facts, facts{}, isFraud}, ... ]
  data/meta.json   ->  population + sample provenance (the true base rate is disclosed)

The fraud label (FraudFound_P) travels INSIDE each claim but is only read by the
scorecard AFTER the model has judged the claim. The model itself never sees it.
"""

import json
import os
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "dataset.csv")
OUT_DIR = os.path.join(HERE, "data")
SEED = 42
N_FRAUD = 40
N_LEGIT = 110

VALUE_BAND = {
    "less than 20000": "Low",
    "20000 to 29000": "Low",
    "30000 to 39000": "Mid",
    "40000 to 59000": "Mid",
    "60000 to 69000": "High",
    "more than 69000": "High",
}


def value_band(price):
    return VALUE_BAND.get(str(price).strip(), "Mid")


def s(v):
    """Clean a cell to a trimmed string; NaN -> ''."""
    if pd.isna(v):
        return ""
    return str(v).strip()


def build_claim(row, cid):
    facts = {
        "make": s(row["Make"]),
        "accidentArea": s(row["AccidentArea"]),
        "fault": s(row["Fault"]),
        "vehiclePrice": s(row["VehiclePrice"]),
        "vehicleCategory": s(row["VehicleCategory"]),
        "policyType": s(row["PolicyType"]),
        "basePolicy": s(row["BasePolicy"]),
        "age": s(row["Age"]),
        "sex": s(row["Sex"]),
        "maritalStatus": s(row["MaritalStatus"]),
        "ageOfVehicle": s(row["AgeOfVehicle"]),
        "ageOfPolicyHolder": s(row["AgeOfPolicyHolder"]),
        "daysPolicyAccident": s(row["Days_Policy_Accident"]),
        "daysPolicyClaim": s(row["Days_Policy_Claim"]),
        "pastNumberOfClaims": s(row["PastNumberOfClaims"]),
        "policeReportFiled": s(row["PoliceReportFiled"]),
        "witnessPresent": s(row["WitnessPresent"]),
        "agentType": s(row["AgentType"]),
        "numberOfSuppliments": s(row["NumberOfSuppliments"]),
        "addressChangeClaim": s(row["AddressChange_Claim"]),
        "deductible": s(row["Deductible"]),
        "driverRating": s(row["DriverRating"]),
    }
    return {
        "id": cid,
        # fields the UI surfaces on each claim row
        "make": facts["make"],
        "area": facts["accidentArea"],
        "fault": facts["fault"],
        "valueBand": value_band(facts["vehiclePrice"]),
        "vehiclePrice": facts["vehiclePrice"],
        "daysToClaim": facts["daysPolicyClaim"],
        "police": facts["policeReportFiled"],
        "prior": facts["pastNumberOfClaims"],
        # full fact sheet handed to the model
        "facts": facts,
        # ground truth, hidden from the model, read only when scoring
        "isFraud": int(row["FraudFound_P"]),
    }


def main():
    df = pd.read_csv(SRC)
    total = len(df)
    fraud_total = int((df["FraudFound_P"] == 1).sum())
    true_rate = fraud_total / total

    fraud = df[df["FraudFound_P"] == 1].sample(n=N_FRAUD, random_state=SEED)
    legit = df[df["FraudFound_P"] == 0].sample(n=N_LEGIT, random_state=SEED)
    sample = pd.concat([fraud, legit]).sample(frac=1, random_state=SEED).reset_index(drop=True)

    claims = [build_claim(row, f"CLM-{1000 + i}") for i, (_, row) in enumerate(sample.iterrows())]

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "claims.js"), "w", encoding="utf-8") as f:
        f.write("// Auto-generated by prep_data.py. Real Kaggle records; label hidden until scored.\n")
        f.write("window.CLAIMS = ")
        json.dump(claims, f, ensure_ascii=False, indent=0)
        f.write(";\n")

    meta = {
        "source": "Kaggle Vehicle Insurance Fraud Detection (fraud_oracle)",
        "population_rows": total,
        "population_fraud": fraud_total,
        "true_fraud_rate": round(true_rate, 4),
        "sample_size": len(claims),
        "sample_fraud": N_FRAUD,
        "sample_legit": N_LEGIT,
        "sample_fraud_rate": round(N_FRAUD / len(claims), 4),
        "seed": SEED,
        "disclosure": (
            "Fraud runs at {:.1%} in the full book. This demo sample is rebalanced to "
            "{:.0%} fraud so there are enough fraud cases to measure precision and recall. "
            "The true base rate is disclosed, not hidden."
        ).format(true_rate, N_FRAUD / len(claims)),
    }
    with open(os.path.join(OUT_DIR, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, ensure_ascii=False, indent=2)

    print("Wrote {} claims ({} fraud / {} legit).".format(len(claims), N_FRAUD, N_LEGIT))
    print("Population {} rows, true fraud rate {:.2%}.".format(total, true_rate))
    print("data/claims.js and data/meta.json written.")


if __name__ == "__main__":
    main()
