runtime: custom
env: flex

# Cloud Run configuration
automatic_scaling:
  min_num_instances: 0
  max_num_instances: 10

resources:
  cpu: 1
  memory_gb: 2

env_variables:
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

# Health check
readiness_check:
  path: "/healthz"
  check_interval_sec: 10
  timeout_sec: 4

liveness_check:
  path: "/healthz"
  check_interval_sec: 10
  timeout_sec: 4