"""
Pre-generated training week data for instant loading.
Scores are derived from each player's base_form with realistic session variation.
Use this in the app for demo/fast mode — run Live Simulation for fresh AI evaluations.
"""

SAMPLE_WEEK = {
    1: {  # Marco Silva — GK
        "name": "Marco Silva", "position": "GK", "age": 28,
        "sessions": {
            "Monday":    {"individual_score": 22, "chemistry_score": 36, "universal_score": 11, "total_score": 69, "highlight": "Excellent distribution and communication during fitness drills.", "concern": "Slightly slow off the line on one crossing drill."},
            "Wednesday": {"individual_score": 26, "chemistry_score": 35, "universal_score": 11, "total_score": 72, "highlight": "Shot-stopping reflexes were sharp in position-specific work.", "concern": "No concerns today"},
            "Thursday":  {"individual_score": 21, "chemistry_score": 38, "universal_score": 11, "total_score": 70, "highlight": "Organised the back four superbly during tactical shape drills.", "concern": "Distribution under pressure needs sharpening."},
            "Friday":    {"individual_score": 24, "chemistry_score": 37, "universal_score": 11, "total_score": 72, "highlight": "Commanding presence — commanded his box well and communicated clearly.", "concern": "No concerns today"},
        },
        "weekly_score": 71.2, "form_score": 71.2,
        "highlight": "Commanding presence — commanded his box well and communicated clearly.",
        "concern": "Distribution under pressure needs sharpening.",
    },
    2: {  # Daniel Park — GK
        "name": "Daniel Park", "position": "GK", "age": 23,
        "sessions": {
            "Monday":    {"individual_score": 17, "chemistry_score": 30, "universal_score": 9, "total_score": 56, "highlight": "Good energy in fitness work, vocal during drills.", "concern": "Aerial claim dropped once — concentration lapse."},
            "Wednesday": {"individual_score": 21, "chemistry_score": 29, "universal_score": 9, "total_score": 59, "highlight": "Made two good one-on-one saves in position drills.", "concern": "Footwork on corners needs improvement."},
            "Thursday":  {"individual_score": 16, "chemistry_score": 33, "universal_score": 9, "total_score": 58, "highlight": "Good communication in pressing shape work.", "concern": "Positioning during set-piece shape needs attention."},
            "Friday":    {"individual_score": 19, "chemistry_score": 31, "universal_score": 9, "total_score": 59, "highlight": "Solid scrimmage — denied two clear chances.", "concern": "Needs more authority coming for crosses."},
        },
        "weekly_score": 58.4, "form_score": 58.4,
        "highlight": "Solid scrimmage — denied two clear chances.",
        "concern": "Needs more authority coming for crosses.",
    },
    3: {  # Carlos Ruiz — DEF
        "name": "Carlos Ruiz", "position": "DEF", "age": 30,
        "sessions": {
            "Monday":    {"individual_score": 22, "chemistry_score": 37, "universal_score": 11, "total_score": 70, "highlight": "Composed and technically crisp throughout conditioning work.", "concern": "No concerns today"},
            "Wednesday": {"individual_score": 26, "chemistry_score": 37, "universal_score": 11, "total_score": 74, "highlight": "Excellent reading of play and distribution in defensive drills.", "concern": "No concerns today"},
            "Thursday":  {"individual_score": 22, "chemistry_score": 40, "universal_score": 11, "total_score": 73, "highlight": "Led the back line through pressing triggers with authority.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 25, "chemistry_score": 39, "universal_score": 12, "total_score": 76, "highlight": "Dominant in the air and on the ball — best defender on the pitch today.", "concern": "No concerns today"},
        },
        "weekly_score": 73.9, "form_score": 73.9,
        "highlight": "Dominant in the air and on the ball — best defender on the pitch today.",
        "concern": "No concerns today",
    },
    4: {  # James Okoye — DEF
        "name": "James Okoye", "position": "DEF", "age": 26,
        "sessions": {
            "Monday":    {"individual_score": 21, "chemistry_score": 35, "universal_score": 11, "total_score": 67, "highlight": "Strong in aerial duels during conditioning headers.", "concern": "Yellow card tendency — one rash challenge flagged."},
            "Wednesday": {"individual_score": 24, "chemistry_score": 34, "universal_score": 10, "total_score": 68, "highlight": "Physical and dominant in one-versus-one defending drills.", "concern": "Ball distribution under pressure remains a weakness."},
            "Thursday":  {"individual_score": 20, "chemistry_score": 37, "universal_score": 10, "total_score": 67, "highlight": "Good defensive shape and pressing coordination.", "concern": "Timing of challenges in pressing shape needs refinement."},
            "Friday":    {"individual_score": 22, "chemistry_score": 36, "universal_score": 11, "total_score": 69, "highlight": "Won every header, blocked two shots — physical presence was key.", "concern": "Distribution from back needs work."},
        },
        "weekly_score": 68.0, "form_score": 68.0,
        "highlight": "Won every header, blocked two shots — physical presence was key.",
        "concern": "Distribution from back needs work.",
    },
    5: {  # Lukas Bauer — DEF
        "name": "Lukas Bauer", "position": "DEF", "age": 29,
        "sessions": {
            "Monday":    {"individual_score": 20, "chemistry_score": 34, "universal_score": 10, "total_score": 64, "highlight": "High stamina shown throughout — completed all conditioning sets.", "concern": "Defensive positioning when caught forward flagged once."},
            "Wednesday": {"individual_score": 23, "chemistry_score": 33, "universal_score": 10, "total_score": 66, "highlight": "Overlapping runs and crossing quality were above average.", "concern": "Recovery speed on transition drills needs attention."},
            "Thursday":  {"individual_score": 19, "chemistry_score": 36, "universal_score": 10, "total_score": 65, "highlight": "Pressing intensity and work rate excellent in shape drills.", "concern": "Needs to track runners more consistently."},
            "Friday":    {"individual_score": 21, "chemistry_score": 35, "universal_score": 10, "total_score": 66, "highlight": "Lively on the right — delivered two quality crosses in the scrimmage.", "concern": "Defensive positioning when caught forward."},
        },
        "weekly_score": 65.4, "form_score": 65.4,
        "highlight": "Lively on the right — delivered two quality crosses in the scrimmage.",
        "concern": "Defensive positioning when caught forward.",
    },
    6: {  # Andre Santos — DEF
        "name": "Andre Santos", "position": "DEF", "age": 24,
        "sessions": {
            "Monday":    {"individual_score": 19, "chemistry_score": 32, "universal_score": 10, "total_score": 61, "highlight": "Good energy and technical quality in conditioning drills.", "concern": "Tracking runs remains an issue — flagged twice."},
            "Wednesday": {"individual_score": 22, "chemistry_score": 31, "universal_score": 10, "total_score": 63, "highlight": "Crisp short passing and solid one-versus-one defending.", "concern": "Positional discipline needs work in transition."},
            "Thursday":  {"individual_score": 18, "chemistry_score": 34, "universal_score": 10, "total_score": 62, "highlight": "Decent contribution in pressing shape and coordination.", "concern": "Tracking runners on right side was inconsistent."},
            "Friday":    {"individual_score": 20, "chemistry_score": 33, "universal_score": 10, "total_score": 63, "highlight": "Solid on the left flank — held his defensive shape well.", "concern": "Tracking runs and positional discipline to improve."},
        },
        "weekly_score": 62.3, "form_score": 62.3,
        "highlight": "Solid on the left flank — held his defensive shape well.",
        "concern": "Tracking runs and positional discipline to improve.",
    },
    7: {  # Tomasz Kowalski — DEF
        "name": "Tomasz Kowalski", "position": "DEF", "age": 32,
        "sessions": {
            "Monday":    {"individual_score": 19, "chemistry_score": 33, "universal_score": 10, "total_score": 62, "highlight": "Led by example in conditioning — good mentoring role.", "concern": "Reduced pace apparent in longer sprints."},
            "Wednesday": {"individual_score": 21, "chemistry_score": 32, "universal_score": 10, "total_score": 63, "highlight": "Excellent organisational role and blocking in drills.", "concern": "Recovery speed flagged in transition work."},
            "Thursday":  {"individual_score": 18, "chemistry_score": 35, "universal_score": 10, "total_score": 63, "highlight": "Strong leader in set-piece shape and defensive organisation.", "concern": "Stamina in extended pressing sequences is a concern."},
            "Friday":    {"individual_score": 20, "chemistry_score": 34, "universal_score": 10, "total_score": 64, "highlight": "Experience showed — organised back line calmly throughout scrimmage.", "concern": "Pace against quick forwards remains a concern."},
        },
        "weekly_score": 63.0, "form_score": 63.0,
        "highlight": "Experience showed — organised back line calmly throughout scrimmage.",
        "concern": "Pace against quick forwards remains a concern.",
    },
    8: {  # Yusuf Amir — DEF
        "name": "Yusuf Amir", "position": "DEF", "age": 21,
        "sessions": {
            "Monday":    {"individual_score": 16, "chemistry_score": 29, "universal_score": 9, "total_score": 54, "highlight": "Pace and athleticism impressive in conditioning work.", "concern": "Rash challenge in one drill — discipline flagged."},
            "Wednesday": {"individual_score": 18, "chemistry_score": 27, "universal_score": 8, "total_score": 53, "highlight": "Good interception work and pressing trigger timing.", "concern": "Inexperience showing — lost shape on two set-piece drills."},
            "Thursday":  {"individual_score": 15, "chemistry_score": 31, "universal_score": 8, "total_score": 54, "highlight": "Showed willingness to press and track runners hard.", "concern": "Rash challenges in pressing sequences — needs control."},
            "Friday":    {"individual_score": 17, "chemistry_score": 29, "universal_score": 9, "total_score": 55, "highlight": "Pace was an asset going forward but defensive gaps appeared.", "concern": "Positional discipline and rash challenges need urgent attention."},
        },
        "weekly_score": 54.2, "form_score": 54.2,
        "highlight": "Pace was an asset going forward but defensive gaps appeared.",
        "concern": "Positional discipline and rash challenges need urgent attention.",
    },
    9: {  # Ricardo Flores — MID
        "name": "Ricardo Flores", "position": "MID", "age": 27,
        "sessions": {
            "Monday":    {"individual_score": 23, "chemistry_score": 38, "universal_score": 12, "total_score": 73, "highlight": "Dictated tempo effortlessly in fitness and conditioning work.", "concern": "No concerns today"},
            "Wednesday": {"individual_score": 27, "chemistry_score": 38, "universal_score": 12, "total_score": 77, "highlight": "Passing range and vision outstanding in position drills.", "concern": "No concerns today"},
            "Thursday":  {"individual_score": 22, "chemistry_score": 42, "universal_score": 12, "total_score": 76, "highlight": "Best player in tactical shape — orchestrated every pressing trigger.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 25, "chemistry_score": 41, "universal_score": 12, "total_score": 78, "highlight": "Controlled the scrimmage from deep — every pass had a purpose.", "concern": "Low scoring threat remains — needs to arrive in box more."},
        },
        "weekly_score": 76.5, "form_score": 76.5,
        "highlight": "Controlled the scrimmage from deep — every pass had a purpose.",
        "concern": "Low scoring threat remains — needs to arrive in box more.",
    },
    10: {  # Kwame Asante — MID
        "name": "Kwame Asante", "position": "MID", "age": 25,
        "sessions": {
            "Monday":    {"individual_score": 21, "chemistry_score": 36, "universal_score": 11, "total_score": 68, "highlight": "Excellent work rate — completed all high-intensity sets.", "concern": "Decision-making in tight spaces was rushed once."},
            "Wednesday": {"individual_score": 24, "chemistry_score": 35, "universal_score": 11, "total_score": 70, "highlight": "Strong pressing and recovery runs in midfield drills.", "concern": "Final ball quality needs improvement."},
            "Thursday":  {"individual_score": 20, "chemistry_score": 38, "universal_score": 11, "total_score": 69, "highlight": "Covered ground brilliantly — best presser in shape drills.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 22, "chemistry_score": 37, "universal_score": 11, "total_score": 70, "highlight": "Box-to-box engine — won the ball back four times in the scrimmage.", "concern": "Final ball quality needs work."},
        },
        "weekly_score": 69.7, "form_score": 69.7,
        "highlight": "Box-to-box engine — won the ball back four times in the scrimmage.",
        "concern": "Final ball quality needs work.",
    },
    11: {  # Mikhail Petrov — MID
        "name": "Mikhail Petrov", "position": "MID", "age": 28,
        "sessions": {
            "Monday":    {"individual_score": 22, "chemistry_score": 37, "universal_score": 11, "total_score": 70, "highlight": "Technically crisp and creative in warm-up drills.", "concern": "Tracking back effort was below standard."},
            "Wednesday": {"individual_score": 26, "chemistry_score": 36, "universal_score": 11, "total_score": 73, "highlight": "Dribbling and key pass frequency were top of the group.", "concern": "Defensive contribution in drills was minimal."},
            "Thursday":  {"individual_score": 21, "chemistry_score": 39, "universal_score": 11, "total_score": 71, "highlight": "Link-up play and combination passing were fluid.", "concern": "Tracking back and defensive responsibilities need improvement."},
            "Friday":    {"individual_score": 24, "chemistry_score": 38, "universal_score": 11, "total_score": 73, "highlight": "Creative spark in scrimmage — two key passes led to clear chances.", "concern": "Tracking back remains a coaching concern."},
        },
        "weekly_score": 71.9, "form_score": 71.9,
        "highlight": "Creative spark in scrimmage — two key passes led to clear chances.",
        "concern": "Tracking back remains a coaching concern.",
    },
    12: {  # Sanjay Kumar — MID
        "name": "Sanjay Kumar", "position": "MID", "age": 26,
        "sessions": {
            "Monday":    {"individual_score": 20, "chemistry_score": 34, "universal_score": 10, "total_score": 64, "highlight": "Disciplined and positionally reliable in conditioning work.", "concern": "No concerns today"},
            "Wednesday": {"individual_score": 23, "chemistry_score": 33, "universal_score": 10, "total_score": 66, "highlight": "Solid screening and short-pass accuracy in midfield drills.", "concern": "Aerial work is a weakness — avoided headers."},
            "Thursday":  {"individual_score": 19, "chemistry_score": 37, "universal_score": 10, "total_score": 66, "highlight": "Held the defensive shape and intercepted well in pressing drills.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 21, "chemistry_score": 36, "universal_score": 10, "total_score": 67, "highlight": "Quiet but effective — screened the defence and kept things tidy.", "concern": "Long-range shots absent — needs to add goal threat."},
        },
        "weekly_score": 65.9, "form_score": 65.9,
        "highlight": "Quiet but effective — screened the defence and kept things tidy.",
        "concern": "Long-range shots absent — needs to add goal threat.",
    },
    13: {  # Omar Hassan — MID
        "name": "Omar Hassan", "position": "MID", "age": 23,
        "sessions": {
            "Monday":    {"individual_score": 18, "chemistry_score": 29, "universal_score": 9, "total_score": 56, "highlight": "Pace and directness shown in wide conditioning runs.", "concern": "Weak foot drills were consistently poor."},
            "Wednesday": {"individual_score": 20, "chemistry_score": 27, "universal_score": 9, "total_score": 56, "highlight": "Crossing quality on strong foot was above average.", "concern": "Tracking back effort was insufficient in defensive drills."},
            "Thursday":  {"individual_score": 17, "chemistry_score": 31, "universal_score": 9, "total_score": 57, "highlight": "Pressing triggers and wide runs showed good energy.", "concern": "Positional discipline in shape work was inconsistent."},
            "Friday":    {"individual_score": 19, "chemistry_score": 29, "universal_score": 9, "total_score": 57, "highlight": "Delivered two good corners and showed pace on the right flank.", "concern": "Tracking back and weak foot remain clear areas for development."},
        },
        "weekly_score": 56.6, "form_score": 56.6,
        "highlight": "Delivered two good corners and showed pace on the right flank.",
        "concern": "Tracking back and weak foot remain clear areas for development.",
    },
    14: {  # Felipe Costa — MID
        "name": "Felipe Costa", "position": "MID", "age": 30,
        "sessions": {
            "Monday":    {"individual_score": 19, "chemistry_score": 33, "universal_score": 10, "total_score": 62, "highlight": "Leadership and composure evident in conditioning drills.", "concern": "Fatigue in final sets — fitness management needed."},
            "Wednesday": {"individual_score": 21, "chemistry_score": 32, "universal_score": 10, "total_score": 63, "highlight": "Set-piece delivery and positional intelligence stood out.", "concern": "Sprint speed clearly reduced compared to younger midfielders."},
            "Thursday":  {"individual_score": 18, "chemistry_score": 35, "universal_score": 10, "total_score": 63, "highlight": "Good reading of pressing triggers and experienced leadership.", "concern": "Stamina in extended pressing sequences is a concern."},
            "Friday":    {"individual_score": 20, "chemistry_score": 34, "universal_score": 10, "total_score": 64, "highlight": "Composed and intelligent — managed the scrimmage tempo well.", "concern": "Sprint recovery between high-intensity bouts needs monitoring."},
        },
        "weekly_score": 63.0, "form_score": 63.0,
        "highlight": "Composed and intelligent — managed the scrimmage tempo well.",
        "concern": "Sprint recovery between high-intensity bouts needs monitoring.",
    },
    15: {  # Jakub Novak — MID
        "name": "Jakub Novak", "position": "MID", "age": 22,
        "sessions": {
            "Monday":    {"individual_score": 17, "chemistry_score": 29, "universal_score": 9, "total_score": 55, "highlight": "High energy and stamina throughout conditioning work.", "concern": "First touch was inconsistent — technical quality to improve."},
            "Wednesday": {"individual_score": 19, "chemistry_score": 27, "universal_score": 9, "total_score": 55, "highlight": "Ball-winning ability and pressing were the standout qualities.", "concern": "Positional discipline in drills was below standard."},
            "Thursday":  {"individual_score": 16, "chemistry_score": 31, "universal_score": 9, "total_score": 56, "highlight": "Quick transitions and pressing energy were impressive.", "concern": "Positional discipline during shape work needs work."},
            "Friday":    {"individual_score": 18, "chemistry_score": 29, "universal_score": 9, "total_score": 56, "highlight": "Energetic scrimmage — won the ball back consistently.", "concern": "First touch and positional discipline need focused work."},
        },
        "weekly_score": 55.7, "form_score": 55.7,
        "highlight": "Energetic scrimmage — won the ball back consistently.",
        "concern": "First touch and positional discipline need focused work.",
    },
    16: {  # Emre Demir — MID
        "name": "Emre Demir", "position": "MID", "age": 24,
        "sessions": {
            "Monday":    {"individual_score": 18, "chemistry_score": 30, "universal_score": 9, "total_score": 57, "highlight": "Technical quality and combination play stood out in drills.", "concern": "Physical duels — tends to avoid contact."},
            "Wednesday": {"individual_score": 20, "chemistry_score": 29, "universal_score": 9, "total_score": 58, "highlight": "Creative dribbling and one-twos were fluid in midfield drills.", "concern": "Aerial challenges consistently avoided."},
            "Thursday":  {"individual_score": 17, "chemistry_score": 32, "universal_score": 9, "total_score": 58, "highlight": "Good combination play in pressing shape — creative link-up.", "concern": "Physical presence in duels remains a weakness."},
            "Friday":    {"individual_score": 19, "chemistry_score": 31, "universal_score": 9, "total_score": 59, "highlight": "Creativity and dribbling caused problems — two chances created.", "concern": "Aerial challenges and physicality remain areas to improve."},
        },
        "weekly_score": 58.1, "form_score": 58.1,
        "highlight": "Creativity and dribbling caused problems — two chances created.",
        "concern": "Aerial challenges and physicality remain areas to improve.",
    },
    17: {  # Antoine Leblanc — FWD
        "name": "Antoine Leblanc", "position": "FWD", "age": 26,
        "sessions": {
            "Monday":    {"individual_score": 21, "chemistry_score": 35, "universal_score": 11, "total_score": 67, "highlight": "Hold-up play and aerial work were top quality in conditioning.", "concern": "No concerns today"},
            "Wednesday": {"individual_score": 25, "chemistry_score": 34, "universal_score": 11, "total_score": 70, "highlight": "Excellent target play and foul-winning in forward drills.", "concern": "Dribbling in tight spaces was limited."},
            "Thursday":  {"individual_score": 21, "chemistry_score": 37, "universal_score": 11, "total_score": 69, "highlight": "Great pressing from the front — set the tone for shape drills.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 23, "chemistry_score": 36, "universal_score": 11, "total_score": 70, "highlight": "Dominant target man — won four aerial duels and held ball up well.", "concern": "Pressing from the front needs more consistency."},
        },
        "weekly_score": 69.3, "form_score": 69.3,
        "highlight": "Dominant target man — won four aerial duels and held ball up well.",
        "concern": "Pressing from the front needs more consistency.",
    },
    18: {  # Hiroshi Tanaka — FWD
        "name": "Hiroshi Tanaka", "position": "FWD", "age": 24,
        "sessions": {
            "Monday":    {"individual_score": 21, "chemistry_score": 34, "universal_score": 11, "total_score": 66, "highlight": "Pace and movement made him a constant threat in conditioning runs.", "concern": "No concerns today"},
            "Wednesday": {"individual_score": 24, "chemistry_score": 33, "universal_score": 11, "total_score": 68, "highlight": "Finishing quality and runs in behind were clinical in drills.", "concern": "Hold-up play and link-up work needs development."},
            "Thursday":  {"individual_score": 20, "chemistry_score": 36, "universal_score": 10, "total_score": 66, "highlight": "Pressing triggers timed well — caused problems for back line.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 22, "chemistry_score": 35, "universal_score": 11, "total_score": 68, "highlight": "Pace in behind created two clear chances in the scrimmage.", "concern": "Hold-up play without the ball needs more effort."},
        },
        "weekly_score": 67.3, "form_score": 67.3,
        "highlight": "Pace in behind created two clear chances in the scrimmage.",
        "concern": "Hold-up play without the ball needs more effort.",
    },
    19: {  # David Mensah — FWD
        "name": "David Mensah", "position": "FWD", "age": 27,
        "sessions": {
            "Monday":    {"individual_score": 22, "chemistry_score": 37, "universal_score": 11, "total_score": 70, "highlight": "Composure and smart movement stood out in conditioning work.", "concern": "No concerns today"},
            "Wednesday": {"individual_score": 26, "chemistry_score": 36, "universal_score": 12, "total_score": 74, "highlight": "Clinical finishing and intelligent positioning in forward drills.", "concern": "Work rate without the ball needs monitoring."},
            "Thursday":  {"individual_score": 22, "chemistry_score": 39, "universal_score": 11, "total_score": 72, "highlight": "Pressing coordination was excellent — best forward in shape drill.", "concern": "No concerns today"},
            "Friday":    {"individual_score": 25, "chemistry_score": 38, "universal_score": 12, "total_score": 75, "highlight": "Two goals and one assist — best forward on the pitch today.", "concern": "No concerns today"},
        },
        "weekly_score": 73.1, "form_score": 73.1,
        "highlight": "Two goals and one assist — best forward on the pitch today.",
        "concern": "No concerns today",
    },
    20: {  # Pavel Cerny — FWD
        "name": "Pavel Cerny", "position": "FWD", "age": 29,
        "sessions": {
            "Monday":    {"individual_score": 19, "chemistry_score": 32, "universal_score": 10, "total_score": 61, "highlight": "Pressing and directness were assets in conditioning work.", "concern": "End product in finishing drills was poor."},
            "Wednesday": {"individual_score": 21, "chemistry_score": 31, "universal_score": 10, "total_score": 62, "highlight": "Dribbling and wide running created good overloads in drills.", "concern": "Shooting accuracy was well below average."},
            "Thursday":  {"individual_score": 18, "chemistry_score": 34, "universal_score": 10, "total_score": 62, "highlight": "Hard-pressing and link-up play were solid in shape work.", "concern": "End product needs urgent improvement."},
            "Friday":    {"individual_score": 20, "chemistry_score": 33, "universal_score": 10, "total_score": 63, "highlight": "Good energy and pressing — made the team work hard defensively.", "concern": "End product and shooting accuracy remain key areas to address."},
        },
        "weekly_score": 62.1, "form_score": 62.1,
        "highlight": "Good energy and pressing — made the team work hard defensively.",
        "concern": "End product and shooting accuracy remain key areas to address.",
    },
    21: {  # Ali Rahman — FWD
        "name": "Ali Rahman", "position": "FWD", "age": 21,
        "sessions": {
            "Monday":    {"individual_score": 16, "chemistry_score": 27, "universal_score": 8, "total_score": 51, "highlight": "Quick feet and creativity shown in warm-up drills.", "concern": "Inconsistency — dropped off significantly in second half of session."},
            "Wednesday": {"individual_score": 18, "chemistry_score": 25, "universal_score": 8, "total_score": 51, "highlight": "Some bright moments in 1v1 finishing drills.", "concern": "Physicality and consistency under pressure remain weak."},
            "Thursday":  {"individual_score": 15, "chemistry_score": 28, "universal_score": 8, "total_score": 51, "highlight": "Showed willingness to press and work for the team.", "concern": "Inconsistency under pressure — loses composure in tight spaces."},
            "Friday":    {"individual_score": 17, "chemistry_score": 26, "universal_score": 8, "total_score": 51, "highlight": "Flashes of creativity but vanished for long stretches.", "concern": "Consistency and physicality need significant improvement."},
        },
        "weekly_score": 51.0, "form_score": 51.0,
        "highlight": "Flashes of creativity but vanished for long stretches.",
        "concern": "Consistency and physicality need significant improvement.",
    },
    22: {  # Bruno Carvalho — FWD
        "name": "Bruno Carvalho", "position": "FWD", "age": 25,
        "sessions": {
            "Monday":    {"individual_score": 18, "chemistry_score": 30, "universal_score": 9, "total_score": 57, "highlight": "Sharp movement and pressing in conditioning work.", "concern": "Contribution outside the box was limited."},
            "Wednesday": {"individual_score": 20, "chemistry_score": 29, "universal_score": 9, "total_score": 58, "highlight": "One-touch finishing quality was good in shooting drills.", "concern": "Assist work and link-up play were below standard."},
            "Thursday":  {"individual_score": 17, "chemistry_score": 32, "universal_score": 9, "total_score": 58, "highlight": "Good pressing effort and movement in shape drill.", "concern": "Box threat only — minimal contribution outside the area."},
            "Friday":    {"individual_score": 19, "chemistry_score": 31, "universal_score": 9, "total_score": 59, "highlight": "Sharp in the box — took one chance well in the scrimmage.", "concern": "Needs to contribute more outside the penalty area."},
        },
        "weekly_score": 58.1, "form_score": 58.1,
        "highlight": "Sharp in the box — took one chance well in the scrimmage.",
        "concern": "Needs to contribute more outside the penalty area.",
    },
}
