[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_APP_NAME = "AI Background Changer"
  VITE_NODE_ENV = "production"

[context.deploy-preview.environment]
  VITE_APP_NAME = "AI Background Changer (Preview)"
  VITE_NODE_ENV = "preview"